spring:
  application:
    name: springboot-redis-demo
  redis:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 1
        max-wait: 10000ms
        max-active: 8
      shutdown-timeout: 100ms
    database: 0
    cluster:
      nodes: 192.168.0.120:7001,192.168.0.120:7002,192.168.0.120:7003



